export const ThemePlayGoals = [
  { id: "goal-drag-one", text: "Drag one thing onto the page", group: "Start Playing" },
  { id: "goal-drag-three", text: "Drag three different elements onto the page", group: "Start Playing" },
  { id: "goal-resize-one", text: "Resize one element", group: "Start Playing" },
  { id: "goal-move-one", text: "Move one element to a new place", group: "Start Playing" },
  { id: "goal-delete-added", text: "Delete something you added", group: "Start Playing" },
  { id: "goal-undo", text: "Undo something", group: "Start Playing" },
  { id: "goal-redo", text: "Redo something", group: "Start Playing" },
  { id: "goal-snap-alignment", text: "Try snapping an element into alignment", group: "Start Playing" },

  { id: "goal-change-fill", text: "Change a fill color", group: "Colors & Palettes" },
  { id: "goal-change-text-color", text: "Change text color", group: "Colors & Palettes" },
  { id: "goal-change-border", text: "Change border color", group: "Colors & Palettes" },
  { id: "goal-apply-three-colors", text: "Apply three colors that belong together", group: "Colors & Palettes" },
  { id: "goal-random-palette", text: "Try one random palette", group: "Colors & Palettes" },
  { id: "goal-save-palette", text: "Save a palette as favorite", group: "Colors & Palettes" },
  { id: "goal-readable-contrast", text: "Use readable contrast", group: "Colors & Palettes" },
  { id: "goal-adjust-global-color", text: "Adjust one global color variable", group: "Colors & Palettes" },

  { id: "goal-create-header", text: "Create a header section", group: "Layout Play" },
  { id: "goal-create-content", text: "Create a content section", group: "Layout Play" },
  { id: "goal-create-footer", text: "Create a footer section", group: "Layout Play" },
  { id: "goal-use-row-column", text: "Use a row or column block", group: "Layout Play" },
  { id: "goal-even-spacing", text: "Place elements evenly spaced", group: "Layout Play" },
  { id: "goal-stack-cards", text: "Stack three cards", group: "Layout Play" },
  { id: "goal-adjust-padding-margin", text: "Use padding or margin sliders", group: "Layout Play" },
  { id: "goal-two-column", text: "Create a two-column layout", group: "Layout Play" },

  { id: "goal-change-font", text: "Change a font", group: "Typography Play" },
  { id: "goal-change-font-size", text: "Change font size", group: "Typography Play" },
  { id: "goal-hierarchy", text: "Create hierarchy: title > heading > body", group: "Typography Play" },
  { id: "goal-letter-weight", text: "Try a different letter weight", group: "Typography Play" },
  { id: "goal-font-pairing", text: "Use one consistent font pairing", group: "Typography Play" },
  { id: "goal-fix-readability", text: "Fix readability over a background", group: "Typography Play" },

  { id: "goal-choose-background", text: "Choose a background", group: "Backgrounds & Texture" },
  { id: "goal-add-gradient", text: "Add a gradient", group: "Backgrounds & Texture" },
  { id: "goal-add-texture", text: "Add a soft texture", group: "Backgrounds & Texture" },
  { id: "goal-random-background", text: "Try a random background", group: "Backgrounds & Texture" },
  { id: "goal-adjust-background-brightness", text: "Adjust background brightness", group: "Backgrounds & Texture" },

  { id: "goal-add-motion", text: "Add a motion preset to one element", group: "Motion & Movement" },
  { id: "goal-add-second-motion", text: "Add a different motion preset to another", group: "Motion & Movement" },
  { id: "goal-remove-motion", text: "Remove motion from something", group: "Motion & Movement" },
  { id: "goal-playful-motion", text: "Make something bounce, float, slide, or fade", group: "Motion & Movement" },
  { id: "goal-preview-motion", text: "Preview motion in Preview Mode", group: "Motion & Movement" },
];
